### ISSUE TITLE
安装后遇到一些问题

### ISSUE THREAD

**Issue by Guoxu233** [thuiar/MMSA#55]
SENA_run is not loaded due to missing dependencies. This is ok if you are not using M-SENA.

请问这个问题怎么解决呢？
麻烦解答一下  感谢

**Comment by FlameSky-S** [comment]
> “SENA_run is not loaded due to missing dependencies. This is ok if you are not using M-SENA.”

这个不影响正常使用。后续会改进提示方式。

第二个问题需要详细信息。

**Comment by IndustryZoe** [comment]
您好，方便留个联系方式吗？想和您交流一下关于您团队的MMSA集成平台，可以吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月12日(周五) 中午11:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thuiar/MMSA] 安装后遇到一些问题 (Issue #55)




  
“SENA_run is not loaded due to missing dependencies. This is ok if you are not using M-SENA.”
  
这个不影响正常使用。后续会改进提示方式。
 
第二个问题需要详细信息。

**Comment by Guoxu233** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda3\envs\pytorch1.12\lib\site-packages\MMSA\run.py", line 186, in MMSA_run
    torch.cuda.set_device(args['device'])
  File "D:\anaconda3\envs\pytorch1.12\lib\site-packages\torch\cuda\__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
请问这个要怎么解决呢

**Comment by IndustryZoe** [comment]
> > “SENA_run is not loaded due to missing dependencies. This is ok if you are not using M-SENA.”
> 
> 这个不影响正常使用。后续会改进提示方式。
> 
> 第二个问题需要详细信息。

您好，请问一下，我把MMSA中的一个模型单独拎出来，然后使用ch-sims数据集训练该模型，发现有些结果中corr有时会变成nan，导致最后的TEST的corr也是nan，比如：“TEST-(LF-DNN) >>  Mult_acc_2: 0.6937  Mult_acc_3: 0.5427  Mult_acc_5: 0.2123  F1_score: 0.5682  MAE: 0.5893  Corr: nan  Loss: 0.5889”这是为什么？在处理这个问题时，MMSA包里具体哪个部分考虑了这个？

**Comment by Columbine21** [comment]
@Chi-Tian 欢迎将自己已发表论文中的模型集成进MMSA框架，可以提PR。如果是模型尝试（未发表）的话也可以使用MMSA框架进行调参，只要格式没问题，是可以使用的。
