### ISSUE TITLE
HOW TO USE API

### ISSUE THREAD

**Issue by HandsomeCBX** [thuiar/MMSA#75]
GET STARTED 1.2 API
HOW TO USE IT?

AND THERE IS AN ERROR
(base) D:\MMSA-master\src\MMSA>python -m MMSA -d mosi -m lmf -s 1111 -s 1112
Traceback (most recent call last):
  File "D:\anacode\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anacode\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anacode\lib\site-packages\MMSA\__main__.py", line 46, in <module>
    MMSA_run(
  File "D:\anacode\lib\site-packages\MMSA\run.py", line 117, in MMSA_run
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), config_file)
FileNotFoundError: [Errno 2] No such file or directory: WindowsPath('.')

**Comment by py-rgb** [comment]
Please refer to the documentation at https://github.com/thuiar/MMSA/wiki/APIs for instructions on API usage. Regarding the error you encountered, it was caused by an incorrect loading path for the config file while using the Windows operating system. To resolve this issue, please modify the command to "python -m MMSA -d mosi -m lmf -s 1111 -s 1112 -c 'save config path'."

**Comment by yuqi555** [comment]
> GET STARTED 1.2 API HOW TO USE IT?
> 
> AND THERE IS AN ERROR (base) D:\MMSA-master\src\MMSA>python -m MMSA -d mosi -m lmf -s 1111 -s 1112 Traceback (most recent call last): File "D:\anacode\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\anacode\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "D:\anacode\lib\site-packages\MMSA__main__.py", line 46, in MMSA_run( File "D:\anacode\lib\site-packages\MMSA\run.py", line 117, in MMSA_run raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), config_file) FileNotFoundError: [Errno 2] No such file or directory: WindowsPath('.')

Hello, I'm sorry to bother you. Have you solved this problem? If so, how did you solve it? I have encountered the same issue. Thank you!
