### ISSUE TITLE
关于CENET模型训练时的报错

### ISSUE THREAD

**Issue by mskmei** [thuiar/MMSA#93]
首先非常感谢团队的工作！

我在按照默认参数训练CENet时（python -m MMSA -d mosi -m cenet -s 1111 -s 1112）遇到了一个意料之外的报错，由于其他模型都可以成功运行所以我想有可能是CENet单独的问题？报错文本如下：
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.10/site-packages/MMSA/__main__.py", line 46, in <module>
    MMSA_run(
  File "/root/miniconda3/lib/python3.10/site-packages/MMSA/run.py", line 221, in MMSA_run
    result = _run(args, num_workers, is_tune)
  File "/root/miniconda3/lib/python3.10/site-packages/MMSA/run.py", line 246, in _run
    model = AMIO(args).to(args['device'])
  File "/root/miniconda3/lib/python3.10/site-packages/MMSA/models/AMIO.py", line 49, in __init__
    self.Model = CENET.from_pretrained(args.pretrained, config=config, pos_tag_embedding=True, senti_embedding=True, polarity_embedding=True, args=args)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_transformers/modeling_utils.py", line 539, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1264, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
**RuntimeError: storage has wrong byte size: expected %ld got %ld03072**

除此以外，训练时模型后面中括号的三个数字可以请教一下分别是什么吗，比如[4/7/1]

**Comment by Columbine21** [comment]
感觉是args.pretrained 的路径指定不太对，这里应该是有点疏忽，cenet 跑起来可能需要按照原仓库中的要求指定pretrained模型路径，具体参考见：https://github.com/Say2L/CENet?tab=readme-ov-file#pre-trained-language-model
